name = "50marches"
main = "src/worker.ts"
compatibility_date = "2023-10-05"
account_id = "05c261edd97f9b2d0ac10037d401b327"
workers_dev = true

routes = [
  { pattern = "50marches.com", custom_domain = true },
  { pattern = "50protests.com", custom_domain = true },
  { pattern = "50marches.org", custom_domain = true }
]

kv_namespaces = [
  { binding = "ASSETS", id = "57171e1463964be4830965c22a832af7", preview_id = "57171e1463964be4830965c22a832af7" }
]

[site]
bucket = "./build"

[build]
command = "npm run build"
cwd = "."

[observability]
logs = { enabled = true }